name: example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  paginate_firestore:
    path: ../
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
