include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - records
    - patterns
  plugins:
    - custom_lint
  # exclude:
  #   - lib/**.g.dart
  #   - lib/**.freezed.dart

custom_lint:
  rules:
    - missing_provider_scope: false

linter:
  rules:
    file_names: false
    prefer_single_quotes: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    require_trailing_commas: true
    join_return_with_assignment: true
    prefer_interpolation_to_compose_strings: true
    prefer_null_aware_method_calls: true
    sized_box_shrink_expand: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_named_constants: true
    use_late_for_private_fields_and_variables: true
    library_private_types_in_public_api: true
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
