name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.0.3+1
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.3
  cloud_firestore: ^4.8.3
  provider: ^6.0.5
  preload_page_view: ^0.2.0
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
